if (self.CavalryLogger) { CavalryLogger.start_js(["Grx4YMA"]); }

__d("useNUXHelpers_nux.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useNUXHelpers_nux",selections:[{kind:"RequiredField",field:{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},action:"THROW",path:"id"},{kind:"RequiredField",field:{alias:null,args:null,kind:"ScalarField",name:"nux_id",storageKey:null},action:"THROW",path:"nux_id"},{kind:"RequiredField",field:{alias:null,args:null,kind:"ScalarField",name:"should_show",storageKey:null},action:"THROW",path:"should_show"}],type:"DefaultNUX",abstractKey:null};e.exports=a}),null);
__d("CometCurrentPageResharesDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3560914130701519",metadata:{},name:"CometCurrentPageResharesDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("useNUXHelpers",["CometRelay","react","useNUX","useNUXHelpers_nux.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h;e=d("react");var i=e.useCallback,j=e.useEffect;function a(a){var e=d("CometRelay").useRelayEnvironment();a=d("CometRelay").useFragment(h!==void 0?h:h=b("useNUXHelpers_nux.graphql"),a);var f=a.id,g=a.nux_id,k=c("useNUX")(g,Boolean(a==null?void 0:a.should_show)),l=k[0],m=k[1],n=a.should_show===!0&&l;k=i(function(){m==null?void 0:m.onDismiss(),d("CometRelay").commitLocalUpdate(e,function(a){a=a.get(f);a==null?void 0:a.setValue(!1,"should_show")})},[m,e,f]);j(function(){n&&(m==null?void 0:m.onVisible())},[g,n,m]);return[n,k]}g["default"]=a}),98);
__d("CometDeferredDialogTrigger.react",["react","useCometDeferredDialog"],(function(a,b,c,d,e,f,g){"use strict";d("react");var h=d("react").useCallback;function a(a){var b=a.children,d=a.dialogProps,e=a.dialogResource,f=a.fallback,g=a.onHide;a=a.onShow;var i=a===void 0?function(){}:a;a=c("useCometDeferredDialog")(e,f);var j=a[0];e=h(function(){j(d,g),i()},[j,d,g,i]);return b(e)}g["default"]=a}),98);
__d("CometDateTimeFormatUtils",["fbt","DateConsts","formatDate"],(function(a,b,c,d,e,f,g,h){"use strict";function a(a,b){return i(a.getJSDate(),b!=null?b.getJSDate():null)}function i(a,b){if(b==null||b.getTime()===a.getTime())if(a.getFullYear()===new Date().getFullYear())return c("formatDate")(a,"M j");else return c("formatDate")(a,"M j, Y");else{var d,e;a.getFullYear()===b.getFullYear()?(a.getFullYear()===new Date().getFullYear()?e=c("formatDate")(b,"M j"):e=c("formatDate")(b,"M j, Y"),d=c("formatDate")(a,"M j")):(d=c("formatDate")(a,"M j, Y"),e=c("formatDate")(b,"M j, Y"));return h._("{start-date} - {end-date}",[h._param("start-date",d),h._param("end-date",e)])}}function b(a){return a==null?null:new Date(a*d("DateConsts").MS_PER_SEC)}g.formatLocalDateRange=a;g.formatDateRange=i;g.getDateFromTimestamp=b}),98);
__d("CometCurrentPageResharesDialog.entrypoint",["CometCurrentPageResharesDialogQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.url;return{queries:{shareQueryReference:{parameters:b("CometCurrentPageResharesDialogQuery$Parameters"),variables:{url:a}}}}},root:c("JSResourceForInteraction")("CometCurrentPageResharesDialog.react").__setRef("CometCurrentPageResharesDialog.entrypoint")};g["default"]=a}),98);
__d("Middot.react",["react","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");c("stylex").inject(".spvqvc9t{clip:rect(0,0,0,0)}",1);c("stylex").inject(".qfa2pajt{clip-path:polygon(0 0,0 0,0 0,0 0)}",1);c("stylex").inject(".s8sjc6am{position:absolute}",1);function a(a){return h.jsxs("span",babelHelpers["extends"]({},a,{children:[h.jsx("span",{className:"s8sjc6am qfa2pajt spvqvc9t",children:"\xa0"}),h.jsx("span",{"aria-hidden":"true",children:" \xb7 "})]}))}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("XCometEventEditControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/events/edit/{event_id}/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("XCometPaidOnlineEventsOnboardingControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/events/poe/onboarding/{?owner_id}/",Object.freeze({disable_deferred_payouts:!1}),void 0);b=a;g["default"]=b}),98);